const productsList = [
    {
      id_product: 1,
      category: "fruta",
      fk_idcategorys: 1,
      name_product: "Laranja",
      price: 1.40,
      unidade: "un",
      image: "./images/produtos/laranja.jpg",
      id_categorys: 1,
      name_categorys: "Fruta",
      selected: false
    },
    {
      id_product: 2,
      category: "fruta",
      fk_idcategorys: 1,
      name_product: "Tangerina",
      price: 1.44,
      unidade: "un",
      image: "./images/produtos/tangerina.jpg",
      id_categorys: 1,
      name_categorys: "Fruta",
      selected: false
    },
    {
      id_product: 3,
      category: "fruta",
      fk_idcategorys: 1,
      name_product: "Limão",
      price: 0.60,
      unidade: "un",
      image: "./images/produtos/limao.jpg",
      id_categorys: 1,
      name_categorys: "Fruta",
      selected: false
    },
    {
      id_product: 4,
      category: "fruta",
      fk_idcategorys: 1,
      name_product: "Morango",
      price: 6.99,
      unidade: "200g",
      image: "./images/produtos/morango.jpg",
      id_categorys: 1,
      name_categorys: "Fruta",
      selected: false
    },
    {
      id_product: 5,
      category: "fruta",
      fk_idcategorys: 1,
      name_product: "Melancia",
      price: 23.17,
      unidade: "un",
      image: "./images/produtos/melancia.jpg",
      id_categorys: 1,
      name_categorys: "Fruta",
      selected: false
    },
    {
      id_product: 6,
      category: "Fruta",
      fk_idcategorys: 1,
      name_product: "Manga",
      price: 3.50,
      unidade: "un",
      image: "./images/produtos/manga.jpg",
      id_categorys: 1,
      name_categorys: "Fruta",
      selected: false
    },
    
    {
      id_product: 7,
      category: "fruta",
      fk_idcategorys: 1,
      name_product: "Maça",
      price: 4.60,
      unidade: "un",
      image: "./images/produtos/maca.jpg",
      id_categorys: 1,
      name_categorys: "Fruta",
      selected: false
    },
    
    {
      id_product: 8,
      category: "fruta",
      fk_idcategorys: 1,
      name_product: "Banana",
      price: 1.40,
      unidade: "un",
      image: "./images/produtos/banana.jpg",
      id_categorys: 1,
      name_categorys: "Fruta",
      selected: false
    },
    {
      id_product: 9,
      category: "legume",
      fk_idcategorys: 2,
      name_product: "Chuchu",
      price: 2.45,
      unidade: "un",
      image: "./images/produtos/chuchu.jpg",
      id_categorys: 2,
      name_categorys: "Legume",
      selected: false
    },
    {
      id_product: 10,
      category: "legume",
      fk_idcategorys: 2,
      name_product: "Pimentão Vermelho",
      price: 5.20,
      unidade: "un",
      image: "./images/produtos/pimentao.jpg",
      id_categorys: 2,
      name_categorys: "Legume",
      selected: false
    },
    {
      id_product: 11,
      category: "diversos",
      fk_idcategorys: 3,
      name_product: "Ovo",
      price: 10.00,
      unidade: "dz",
      image: "./images/produtos/ovo.jpg",
      id_categorys: 3,
      name_categorys: "Diversos",
      selected: false
    },
    {
      id_product: 12,
      category: "diversos",
      fk_idcategorys: 3,
      name_product: "Cesta",
      price: 89.99,
      unidade: "kit",
      image: "./images/produtos/cesta.jpg",
      id_categorys: 3,
      name_categorys: "Diversos",
      selected: false
    },
    {
      id_product: 13,
      category: "diversos",
      fk_idcategorys: 3,
      name_product: "Pão Francês",
      price: 1.00,
      unidade: "un",
      image: "./images/produtos/pao.jpg",
      id_categorys: 3,
      name_categorys: "Diversos",
      selected: false
    },
    {
      id_product: 14,
      category: "legume",
      fk_idcategorys: 2,
      name_product: "Batata Inglesa",
      price: 1.00,
      unidade: "un",
      image: "./images/produtos/batata-inglesa.jpg",
      id_categorys: 2,
      name_categorys: "Legume",
      selected: false
    },
    {
      id_product: 15,
      category: "verdura",
      fk_idcategorys: 4,
      name_product: "Salsinha",
      price: 5.99,
      unidade: "maço",
      image: "./images/produtos/salsinha.jpg",
      id_categorys: 4,
      name_categorys: "Verdura",
      selected: false
    },
    {
      id_product: 16,
      category: "verdura",
      fk_idcategorys: 4,
      name_product: "Coentro",
      price: 5.99,
      unidade: "maço",
      image: "./images/produtos/coentro.jpg",
      id_categorys: 4,
      name_categorys: "Verdura",
      selected: false
    },
    {
      id_product: 17,
      category: "legume",
      fk_idcategorys: 2,
      name_product: "Cenoura",
      price: 0.64,
      unidade: "un",
      image: "./images/produtos/cenoura.jpg",
      id_categorys: 2,
      name_categorys: "Legume",
      selected: false
    },
    {
      id_product: 18,
      category: "verdura",
      fk_idcategorys: 4,
      name_product: "Catalonha",
      price: 5.99,
      unidade: "un",
      image: "./images/produtos/catalonha.jpg",
      id_categorys: 4,
      name_categorys: "Verdura",
      selected: false
    },
    {
      id_product: 19,
      category: "verdura",
      fk_idcategorys: 4,
      name_product: "Alface Hidro",
      price: 5.99,
      unidade: "un",
      image: "./images/produtos/alface.jpg",
      id_categorys: 4,
      name_categorys: "Verdura",
      selected: false
    },
    {
      id_product: 20,
      category: "legume",
      fk_idcategorys: 2,
      name_product: "Tomate Salada",
      price: 4.99,
      unidade: "un",
      image: "./images/produtos/tomate.jpg",
      id_categorys: 2,
      name_categorys: "Legume",
      selected: false
    },
    {
      id_product: 21,
      category: "legume",
      fk_idcategorys: 2,
      name_product: "Pepino",
      price: 0.99,
      unidade: "un",
      image: "./images/produtos/pepino.jpg",
      id_categorys: 2,
      name_categorys: "Legume",
      selected: false
    },
    {
      id_product: 22,
      category: "legume",
      fk_idcategorys: 2,
      name_product: "Beterraba",
      price: 3.60,
      unidade: "un",
      image: "./images/produtos/beterraba.jpg",
      id_categorys: 2,
      name_categorys: "Legume",
      selected: false
    },
    {
      id_product: 22,
      category: "legume",
      fk_idcategorys: 2,
      name_product: "Tomate Cereja",
      price: 5.37,
      unidade: "300 gr",
      image: "./images/produtos/tomate-cereja.jpg",
      id_categorys: 2,
      name_categorys: "Legume",
      selected: false
    },
];

export default productsList;

